spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/library_management_system?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  global-config:
    db-config:
      table-prefix:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:Dao/*.xml


server:
  port: 8080
file:
  upload-dir: D:/uploads
swagger:
  enable: true
